---
- hosts: routers
  become: yes

  tasks:
    - name: Create Loopback888
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback888
            description: Configured and Overridden by Ansible Network
            enabled: true

    - name: Add IOP address tp L888
      cisco.ios.ios_l3_interfaces:
        name: Loopback888
        ipv4: 192.168.255.88/32
