---
datacenter:
  chlidren:
    routers:
      hosts:
        10.0.0.24[1:2]:

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: tony
    ansible_password: cisco
    ntp_servers:
      - 10.0.0.100
      - 10.0.0.200
